//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witlesss.Also {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Witlesss.Also.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправь эту команду вместе со словом, и я сгенерю чё-нибудь, начиная с него (если оно есть в словаре).
        /// </summary>
        internal static string A_MANUAL {
            get {
                return ResourceManager.GetString("A_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string BACKUP_FOLDER {
            get {
                return ResourceManager.GetString("BACKUP_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @piece_fap_bot.
        /// </summary>
        internal static string BOT_USERNAME {
            get {
                return ResourceManager.GetString("BOT_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram-ChatsDB.
        /// </summary>
        internal static string CHATLIST_FILENAME {
            get {
                return ResourceManager.GetString("CHATLIST_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напиши это вместе с видосом или музлом.
        /// </summary>
        internal static string DAMN_MANUAL {
            get {
                return ResourceManager.GetString("DAMN_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram-WitlessDB.
        /// </summary>
        internal static string DB_FILE_PREFIX {
            get {
                return ResourceManager.GetString("DB_FILE_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram-WitlessDBs.
        /// </summary>
        internal static string DBS_FOLDER {
            get {
                return ResourceManager.GetString("DBS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram-Messages.
        /// </summary>
        internal static string DEBUG_FOLDER {
            get {
                return ResourceManager.GetString("DEBUG_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Sans MS.
        /// </summary>
        internal static string DEMOTIVATOR_LOWER_FONT {
            get {
                return ResourceManager.GetString("DEMOTIVATOR_LOWER_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times New Roman.
        /// </summary>
        internal static string DEMOTIVATOR_UPPER_FONT {
            get {
                return ResourceManager.GetString("DEMOTIVATOR_UPPER_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для генерации демотиватора отправь мне эту команду вместе с фото или в ответ на фото.
        /// </summary>
        internal static string DG_MANUAL {
            get {
                return ResourceManager.GetString("DG_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram-ExtraDBs.
        /// </summary>
        internal static string EXTRA_DBS_FOLDER {
            get {
                return ResourceManager.GetString("EXTRA_DBS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ffmpeg\bin\ffmpeg.exe.
        /// </summary>
        internal static string FFMPEG_PATH {
            get {
                return ResourceManager.GetString("FFMPEG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, я не нашёл словаря с таким названием.
        /// </summary>
        internal static string FUSE_FAIL_BASE {
            get {
                return ResourceManager.GetString("FUSE_FAIL_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, у меня нет словаря этой беседы.
        /// </summary>
        internal static string FUSE_FAIL_CHAT {
            get {
                return ResourceManager.GetString("FUSE_FAIL_CHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты собираешься слить эту беседу... с этой же беседой? Ничего не поменяется, лол.
        /// </summary>
        internal static string FUSE_FAIL_SELF {
            get {
                return ResourceManager.GetString("FUSE_FAIL_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы хотите объединить словарь &lt;b&gt;этой беседы&lt;/b&gt; со словарём &lt;b&gt;другой беседы&lt;/b&gt;, где я состою и где есть вы, то для начала скопируйте &lt;b&gt;ID той беседы&lt;/b&gt; с помощью команды
        ///
        ////chat_id@piece_fap_bot
        ///
        ///и пропишите &lt;b&gt;здесь&lt;/b&gt;
        ///
        ////fuse@piece_fap_bot [полученное число]
        ///
        ///пример: /fuse@piece_fap_bot -1001541923355
        ///
        ///Слияние разово обновит словарь &lt;b&gt;этой беседы&lt;/b&gt;.
        /// </summary>
        internal static string FUSE_MANUAL {
            get {
                return ResourceManager.GetString("FUSE_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cловарь беседы.
        /// </summary>
        internal static string FUSE_SUCCESS_RESPONSE_A {
            get {
                return ResourceManager.GetString("FUSE_SUCCESS_RESPONSE_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обновлён!.
        /// </summary>
        internal static string FUSE_SUCCESS_RESPONSE_B {
            get {
                return ResourceManager.GetString("FUSE_SUCCESS_RESPONSE_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHATLIST SAVED.
        /// </summary>
        internal static string LOG_CHATLIST_SAVED {
            get {
                return ResourceManager.GetString("LOG_CHATLIST_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUSION DONE.
        /// </summary>
        internal static string LOG_FUSE_DONE {
            get {
                return ResourceManager.GetString("LOG_FUSE_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICS HERE.
        /// </summary>
        internal static string LOG_FUSION_HAVE_DICS {
            get {
                return ResourceManager.GetString("LOG_FUSION_HAVE_DICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копия словаря сохранена как.
        /// </summary>
        internal static string MOVE_DONE_AS {
            get {
                return ResourceManager.GetString("MOVE_DONE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Словарь очищен! *пусто*.
        /// </summary>
        internal static string MOVE_DONE_CLEARED {
            get {
                return ResourceManager.GetString("MOVE_DONE_CLEARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы хотите очистить словарь беседы, пропишите
        ///
        ////move@piece_fap_bot [имя]
        ///
        ///Эта команда сохранит &lt;b&gt;копию словаря&lt;/b&gt; под указанным именем и очистит &lt;b&gt;сам словарь&lt;/b&gt;. Зная имя, вы можете в любой момент &lt;b&gt;влить&lt;/b&gt; сохранённую копию в словарь беседы, прописав
        ///
        ////fuse@piece_fap_bot [имя].
        /// </summary>
        internal static string MOVE_MANUAL {
            get {
                return ResourceManager.GetString("MOVE_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram-Pictures.
        /// </summary>
        internal static string PICTURES_FOLDER {
            get {
                return ResourceManager.GetString("PICTURES_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если че правильно вот так:
        ///
        ///set@piece_fap_bot 3
        ///
        ///(чем меньше значение - тем чаще я буду писать).
        /// </summary>
        internal static string SET_FREQUENCY_MANUAL {
            get {
                return ResourceManager.GetString("SET_FREQUENCY_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я буду отвечать на.
        /// </summary>
        internal static string SET_FREQUENCY_RESPONSE_A {
            get {
                return ResourceManager.GetString("SET_FREQUENCY_RESPONSE_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пикчи будут ставать демотиваторами с вероятностью.
        /// </summary>
        internal static string SET_FREQUENCY_RESPONSE_B {
            get {
                return ResourceManager.GetString("SET_FREQUENCY_RESPONSE_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если че правильно вот так:
        ///
        ///set_p@piece_fap_bot 75.
        /// </summary>
        internal static string SET_PROBABILITY_MANUAL {
            get {
                return ResourceManager.GetString("SET_PROBABILITY_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВИРУСНАЯ БАЗА ОБНОВЛЕНА!.
        /// </summary>
        internal static string START_RESPONSE {
            get {
                return ResourceManager.GetString("START_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram-Water.
        /// </summary>
        internal static string WATERMARKS_FOLDER {
            get {
                return ResourceManager.GetString("WATERMARKS_FOLDER", resourceCulture);
            }
        }
    }
}
